# Generated by Django 5.2.3 on 2025-06-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurant', '0002_rename_reservation_date_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='restaurant_users', to='auth.group')),
            ],
            options={
                'verbose_name': 'Restaurant User',
                'verbose_name_plural': 'Restaurant Users',
            },
        ),
    ]
