# Generated by Django 5.2.3 on 2025-06-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_slots',
            field=models.CharField(default='', max_length=100),
        ),
    ]
